#!/usr/bin/env python3
import subprocess, shutil, pickle, glob, sys, os
from pprint import pprint

def main(args):
    assert len(args) == 2
    directory, comparison = args

    filenames = glob.glob(directory + '*')
    print(filenames)
    tree = {}
    for i, file_left in enumerate(filenames):
        for file_right in filenames[i+1:]:
            tree[file_left + 'x'+ file_right] = (
                subprocess.check_output([comparison, file_left, file_right]).decode('utf-8'))
    with open('output.pkl', 'wb') as outfile:
        pickle.dump(tree, outfile)
    pprint(tree)
    
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
