#!/usr/bin/env python3
import subprocess, shutil, sys, os

def main(args):
    assert len(args) > 3
    print(args)
    command, directory, datafile, *branches = args
    datadir = directory.replace('/', '_') + '_data'

    if not os.path.exists(datadir):
        os.mkdir(datadir)

    original = os.getcwd()
    os.chdir(directory)
    for branch in branches:
        subprocess.call(['git', 'checkout', branch])
        sha = subprocess.check_output(['git', 'rev-parse', branch])
        sha = sha.decode('utf-8').replace('\n', '')
        subprocess.call(command.split(' '))
        shutil.move(datafile, original + '/' + datadir + '/' + sha)
    os.chdir(original)
        
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
